//! Parse the C header `mmutil` emits and re-emit it as a Rust module.
//!
//! `mmutil -h` writes lines like `#define SFX_BLIP_SELECT    1` (one per WAV
//! sample), `#define MOD_SONG 0` (one per tracker module) and the bank
//! `#define MSL_NSONGS 0` / `MSL_NSAMPS 2` counts. We turn those into Rust
//! `pub const`s so game code references sounds by name with no manual sync.
//!
//! Pure (string in, string out) so it is unit tested on the host.

/// One `#define NAME VALUE` parsed from the header.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Define {
    pub name: String,
    pub value: u32,
}

/// Parse every `#define <IDENT> <number>` line, ignoring everything else.
pub fn parse_header(header: &str) -> Vec<Define> {
    let mut out = Vec::new();
    for line in header.lines() {
        let line = line.trim();
        let Some(rest) = line.strip_prefix("#define") else {
            continue;
        };
        let mut parts = rest.split_whitespace();
        let (Some(name), Some(value)) = (parts.next(), parts.next()) else {
            continue;
        };
        // Only keep simple numeric defines (the IDs and counts).
        if let Ok(value) = value.parse::<u32>() {
            out.push(Define {
                name: name.to_string(),
                value,
            });
        }
    }
    out
}

/// Render parsed defines as a Rust module body of `pub const <NAME>: u32 = N;`.
///
/// `SFX_*` and `MOD_*` are documented as sound IDs; the `MSL_*` counts are kept
/// too. The output is deterministic (input order) and `include!`-able from the
/// audio crate or a build script's `OUT_DIR`.
pub fn emit_rust(defines: &[Define]) -> String {
    let mut s = String::new();
    s.push_str("// @generated by wav2bank from the mmutil soundbank header.\n");
    s.push_str("// Each constant is the numeric ID maxmod assigns to a sound in\n");
    s.push_str("// `soundbank.bin`. Pass `SFX_*` to `mmEffect`/`mmLoadEffect` and\n");
    s.push_str("// `MOD_*` to `mmStart`/`mmLoad`.\n");
    for d in defines {
        let doc = if d.name.starts_with("SFX_") {
            "/// Sound-effect (sample) ID for `mmEffect`/`mmLoadEffect`.\n"
        } else if d.name.starts_with("MOD_") {
            "/// Module (song) ID for `mmStart`/`mmLoad`.\n"
        } else {
            "/// Soundbank metadata emitted by mmutil.\n"
        };
        s.push_str(doc);
        s.push_str("pub const ");
        s.push_str(&d.name);
        s.push_str(": u32 = ");
        s.push_str(&d.value.to_string());
        s.push_str(";\n");
    }
    s
}

/// Convert a sample's file stem to the constant name `mmutil` would assign:
/// upper-cased, non-alphanumerics turned to `_`, with an `SFX_` prefix.
pub fn sample_const_name(stem: &str) -> String {
    let mut s = String::from("SFX_");
    for c in stem.chars() {
        if c.is_ascii_alphanumeric() {
            s.push(c.to_ascii_uppercase());
        } else {
            s.push('_');
        }
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = "\
#define SFX_PIANO_LOOP    0
#define SFX_BLIP_SELECT    1
#define MSL_NSONGS    0
#define MSL_NSAMPS    2
#define MSL_BANKSIZE    2
";

    #[test]
    fn parses_all_numeric_defines() {
        let d = parse_header(SAMPLE);
        assert_eq!(d.len(), 5);
        assert_eq!(
            d[0],
            Define {
                name: "SFX_PIANO_LOOP".into(),
                value: 0
            }
        );
        assert_eq!(
            d[1],
            Define {
                name: "SFX_BLIP_SELECT".into(),
                value: 1
            }
        );
        assert_eq!(
            d[3],
            Define {
                name: "MSL_NSAMPS".into(),
                value: 2
            }
        );
    }

    #[test]
    fn ignores_non_numeric_and_blank_lines() {
        let h = "#define FOO bar\n\n// comment\n#define SFX_X 3\n#pragma once\n";
        let d = parse_header(h);
        assert_eq!(
            d,
            vec![Define {
                name: "SFX_X".into(),
                value: 3
            }]
        );
    }

    #[test]
    fn emits_consts_for_each_define() {
        let d = parse_header(SAMPLE);
        let rs = emit_rust(&d);
        assert!(rs.contains("pub const SFX_PIANO_LOOP: u32 = 0;"));
        assert!(rs.contains("pub const SFX_BLIP_SELECT: u32 = 1;"));
        assert!(rs.contains("pub const MSL_NSAMPS: u32 = 2;"));
        // SFX constants carry the effect doc-comment.
        assert!(rs.contains("Sound-effect (sample) ID"));
    }

    #[test]
    fn output_is_deterministic() {
        let d = parse_header(SAMPLE);
        assert_eq!(emit_rust(&d), emit_rust(&d));
    }

    #[test]
    fn sample_const_names_match_mmutil() {
        assert_eq!(sample_const_name("piano_loop"), "SFX_PIANO_LOOP");
        assert_eq!(sample_const_name("blip_select"), "SFX_BLIP_SELECT");
        assert_eq!(sample_const_name("hit-01"), "SFX_HIT_01");
    }
}
